### ISSUE TITLE
[Feature request] Get scores of leaderboard

### ISSUE THREAD

**Issue by tssmobile** [Abedalkareem/games_services#38] opened 2021-08-07 08:14 UTC
Is there a plan to release the feature that only returns the leaderboard scores for easy customizing the UI instead of the default UI?

**Comment by EliaTolin** [comment] 2022-02-24 13:06
@Abedalkareem news?

**Comment by intercretasyo** [comment] 2022-03-16 16:20
This would be good. I tried to tweak it to learn how can this be coded, but I really can't figure out how.

**Comment by Abedalkareem** [comment] 2022-08-21 03:15
Duplicate of #33

**Closed by Abedalkareem** 2022-08-21 03:15 UTC
Labels: enhancement
